-- using sqlite3!!!!!!
-- it was very uneasy to create a more than 100 cols schemas

DROP TABLE IF EXISTS `daily`;
CREATE TABLE IF NOT EXISTS `daily`
(
    `id`   INTEGER PRIMARY KEY AUTOINCREMENT,
    `dish` INTEGER NOT NULL,
    `date` CHAR(20)    NOT NULL,
    `time` INTEGER NOT NULL
);

DROP TABLE IF EXISTS `dishes`;
CREATE TABLE IF NOT EXISTS `dishes`
(
    `id` INTEGER PRIMARY KEY AUTOINCREMENT ,
    `name` CHAR(50) NOT NULL ,
    `category` INTEGER NOT NULL ,
    `recipe` INTEGER NOT NULL
);

DROP TABLE IF EXISTS `recipe`;
CREATE TABLE IF NOT EXISTS `recipe`
(
    `id`        INTEGER PRIMARY KEY AUTOINCREMENT ,
    `wu_hua_rou`DOUBLE DEFAULT 0,
    `pai_gu`DOUBLE DEFAULT 0,
    `rou_mo`DOUBLE DEFAULT 0,
    `shou_rou_pian`DOUBLE DEFAULT 0,
    `shou_rou_si`DOUBLE DEFAULT 0,
    `zhu_xue`DOUBLE DEFAULT 0,
    `zhu_gan`DOUBLE DEFAULT 0,
    `huo_tui`DOUBLE DEFAULT 0,
    `lu_zhu_tou_rou`DOUBLE DEFAULT 0,
    `zhu_ti`DOUBLE DEFAULT 0,
    `lu_da_chang`DOUBLE DEFAULT 0,
    `zhu_du`DOUBLE DEFAULT 0,
    `pei_gen`DOUBLE DEFAULT 0,
    `la_rou`DOUBLE DEFAULT 0,
    `zhou_zi`DOUBLE DEFAULT 0,
    `niu_rou`DOUBLE DEFAULT 0,
    `niu_gu`DOUBLE DEFAULT 0,
    `niu_li_ji_rou`DOUBLE DEFAULT 0,
    `niu_nan`DOUBLE DEFAULT 0,
    `shu_niu_za`DOUBLE DEFAULT 0,
    `yang_rou`DOUBLE DEFAULT 0,
    `yang_pai`DOUBLE DEFAULT 0,
    `wu_xiang_ban_ya`DOUBLE DEFAULT 0,
    `ya_bian_tui`DOUBLE DEFAULT 0,
    `ya_zhen`DOUBLE DEFAULT 0,
    `wu_ji`DOUBLE DEFAULT 0,
    `ji_mi_hua`DOUBLE DEFAULT 0,
    `bai_tiao_ji`DOUBLE DEFAULT 0,
    `ji_xiong_rou`DOUBLE DEFAULT 0,
    `chi_zhong`DOUBLE DEFAULT 0,
    `pi_pa_tui`DOUBLE DEFAULT 0,
    `ya_rou`DOUBLE DEFAULT 0,
    `ao_er_liang_ji_pai`DOUBLE DEFAULT 0,
    `yan_shui_ya`DOUBLE DEFAULT 0,
    `kao_ya`DOUBLE DEFAULT 0,
    `tu_rou`DOUBLE DEFAULT 0,
    `tian_ji`DOUBLE DEFAULT 0,
    `cao_yu`DOUBLE DEFAULT 0,
    `xiao_huang_yu`DOUBLE DEFAULT 0,
    `huang_gua_yu`DOUBLE DEFAULT 0,
    `lu_yu`DOUBLE DEFAULT 0,
    `rou_`DOUBLE DEFAULT 0,
    `qiu_dao_yu`DOUBLE DEFAULT 0,
    `ya_pian_yu_tou`DOUBLE DEFAULT 0,
    `ba_sha_yu_liu`DOUBLE DEFAULT 0,
    `dai_yu`DOUBLE DEFAULT 0,
    `ji_yu`DOUBLE DEFAULT 0,
    `you_yu`DOUBLE DEFAULT 0,
    `jin_chang_yu`DOUBLE DEFAULT 0,
    `qing_e`DOUBLE DEFAULT 0,
    `bao_yu`DOUBLE DEFAULT 0,
    `hua_ge`DOUBLE DEFAULT 0,
    `xia`DOUBLE DEFAULT 0,
    `pang_xie`DOUBLE DEFAULT 0,
    `xia_ren`DOUBLE DEFAULT 0,
    `pang_yu_tou`DOUBLE DEFAULT 0,
    `hai_li`DOUBLE DEFAULT 0,
    `hai_cheng`DOUBLE DEFAULT 0,
    `hai_hong`DOUBLE DEFAULT 0,
    `bao_gong_yu`DOUBLE DEFAULT 0,
    `hu_gua`DOUBLE DEFAULT 0,
    `dong_gua`DOUBLE DEFAULT 0,
    `da_bai_cai`DOUBLE DEFAULT 0,
    `kuan_fen`DOUBLE DEFAULT 0,
    `bai_luo_bo`DOUBLE DEFAULT 0,
    `hong_luo_bo`DOUBLE DEFAULT 0,
    `huang_dou_ya`DOUBLE DEFAULT 0,
    `lv_dou_ya`DOUBLE DEFAULT 0,
    `hong_cai_jiao`DOUBLE DEFAULT 0,
    `cai_jiao`DOUBLE DEFAULT 0,
    `huang_cai_jiao`DOUBLE DEFAULT 0,
    `qing_jian_jiao`DOUBLE DEFAULT 0,
    `hong_jian_jiao`DOUBLE DEFAULT 0,
    `xiao_qing_mi_jiao`DOUBLE DEFAULT 0,
    `xiao_hong_mi_jiao`DOUBLE DEFAULT 0,
    `pao_jiao`DOUBLE DEFAULT 0,
    `suan_tai`DOUBLE DEFAULT 0,
    `yang_cong`DOUBLE DEFAULT 0,
    `huang_gua`DOUBLE DEFAULT 0,
    `shi_mu_er`DOUBLE DEFAULT 0,
    `xing_bao_gu`DOUBLE DEFAULT 0,
    `hai_xian_gu`DOUBLE DEFAULT 0,
    `lian_ou`DOUBLE DEFAULT 0,
    `dong_sun`DOUBLE DEFAULT 0,
    `tu_dou`DOUBLE DEFAULT 0,
    `jiao_bai`DOUBLE DEFAULT 0,
    `wo_sun`DOUBLE DEFAULT 0,
    `si_ji_dou`DOUBLE DEFAULT 0,
    `di_gua`DOUBLE DEFAULT 0,
    `shan_yao`DOUBLE DEFAULT 0,
    `xi_qin`DOUBLE DEFAULT 0,
    `bao_cai`DOUBLE DEFAULT 0,
    `da_cong`DOUBLE DEFAULT 0,
    `chang_gan_dou`DOUBLE DEFAULT 0,
    `xi_hong_shi`DOUBLE DEFAULT 0,
    `si_gua`DOUBLE DEFAULT 0,
    `jiu_cai`DOUBLE DEFAULT 0,
    `jiu_huang`DOUBLE DEFAULT 0,
    `ku_gua`DOUBLE DEFAULT 0,
    `hua_cai`DOUBLE DEFAULT 0,
    `he_lan_dou`DOUBLE DEFAULT 0,
    `wa_wa_cai`DOUBLE DEFAULT 0,
    `xiang_gu_gong_wan`DOUBLE DEFAULT 0,
    `yu_tou`DOUBLE DEFAULT 0,
    `qian_ye_dou_fu`DOUBLE DEFAULT 0,
    `dou_fu`DOUBLE DEFAULT 0,
    `dou_pao`DOUBLE DEFAULT 0,
    `lu_xiang_gan`DOUBLE DEFAULT 0,
    `shang_hai_qing`DOUBLE DEFAULT 0,
    `tian_jin_bai`DOUBLE DEFAULT 0,
    `jie_cai`DOUBLE DEFAULT 0,
    `sheng_cai`DOUBLE DEFAULT 0,
    `kong_xin_cai`DOUBLE DEFAULT 0,
    `cai_xin`DOUBLE DEFAULT 0,
    `hong_xian_cai`DOUBLE DEFAULT 0,
    `jin_zhen_gu`DOUBLE DEFAULT 0,
    `qiu_kui`DOUBLE DEFAULT 0,
    `bo_cai`DOUBLE DEFAULT 0,
    `mu_er_cai`DOUBLE DEFAULT 0,
    `yu_hua`DOUBLE DEFAULT 0,
    `yu_wan`DOUBLE DEFAULT 0,
    `rou_yan`DOUBLE DEFAULT 0,
    `yu_mi_li`DOUBLE DEFAULT 0,
    `mian_jin`DOUBLE DEFAULT 0,
    `hai_dai_jie`DOUBLE DEFAULT 0,
    `fu_zhu`DOUBLE DEFAULT 0,
    `an_chun_dan`DOUBLE DEFAULT 0,
    `gan_cha_shu_gu`DOUBLE DEFAULT 0,
    `yu_mi`DOUBLE DEFAULT 0,
    `dou_jie`DOUBLE DEFAULT 0,
    `pao_fa_sun_gan`DOUBLE DEFAULT 0,
    `nuo_mi`DOUBLE DEFAULT 0,
    `zheng_rou_fen`DOUBLE DEFAULT 0,
    `suan_miao`DOUBLE DEFAULT 0,
    `mei_cai_gan`DOUBLE DEFAULT 0,
    `suan_cai`DOUBLE DEFAULT 0,
    `xiang_cai`DOUBLE DEFAULT 0,
    `lao_jiang`DOUBLE DEFAULT 0,
    `bing_lang_yu`DOUBLE DEFAULT 0,
    `ping_gu`DOUBLE DEFAULT 0,
    `xue_li_hong`DOUBLE DEFAULT 0,
    `hai_ying_xiang_chang`DOUBLE DEFAULT 0,
    `qie_zi`DOUBLE DEFAULT 0
);

DROP TABLE IF EXISTS `daily_num`;
CREATE TABLE IF NOT EXISTS `daily_num`
(
    `id`      INTEGER PRIMARY KEY AUTOINCREMENT ,
    `date`    CHAR(20)    NOT NULL,
    `num`     INTEGER DEFAULT 0
);


